// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcXOPe0bB4DZvytqX9VvEZIwYQzRogT4',
    appId: '1:1044813949080:web:bfc3ec6ab85e06ed6148ed',
    messagingSenderId: '1044813949080',
    projectId: 'flutterapp-75fee',
    authDomain: 'flutterapp-75fee.firebaseapp.com',
    storageBucket: 'flutterapp-75fee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMZrAmbBIJYxuoT443oxEM76DoyclYbes',
    appId: '1:1044813949080:android:4a3ca52654f5f5dd6148ed',
    messagingSenderId: '1044813949080',
    projectId: 'flutterapp-75fee',
    storageBucket: 'flutterapp-75fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIO1kgovwf_pJAyzsElKK0vM93TJGpM08',
    appId: '1:1044813949080:ios:f65a50aaa1fd783f6148ed',
    messagingSenderId: '1044813949080',
    projectId: 'flutterapp-75fee',
    storageBucket: 'flutterapp-75fee.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIO1kgovwf_pJAyzsElKK0vM93TJGpM08',
    appId: '1:1044813949080:ios:7be9e1528b5f3f8c6148ed',
    messagingSenderId: '1044813949080',
    projectId: 'flutterapp-75fee',
    storageBucket: 'flutterapp-75fee.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
